/*! \file
 *
 * \author Emmanuel Dean
 *
 * \version 0.1
 * \date 15.03.2021
 *
 * \copyright Copyright 2021 Chalmers
 *
 * #### License
 * All rights reserved.
 *
 * Software License Agreement (BSD License 2.0)
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include <robot_2w_ctrl/Robot2WCtrl.h>

#include <rcl_interfaces/msg/parameter_type.hpp>

#include <tf2/transform_datatypes.h>
#include <geometry_msgs/msg/quaternion.hpp>
#include <tf2_ros/transform_broadcaster.h>

#include <tf2_eigen/tf2_eigen.hpp>
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include <tf2/convert.h>

#define DEG2RAD(DEG) ((DEG) * ((M_PI) / (180.0)))
#define RAD2DEG(RAD) ((RAD) * ((180.0) / (M_PI)))

using std::placeholders::_1;

namespace robot_2w_examples
{
Robot2WCtrl::Robot2WCtrl(/* args */)
  : Node("robot_2w_control"), K_(Eigen::Matrix3d::Zero()), first_message_(false), init_ctrl_(true), got_odom_(false)
{
  // Init Parameters. Load node parameters
  init();

  // Set parameter callback function
  callback_handle_ = this->add_on_set_parameters_callback(std::bind(&Robot2WCtrl::parametersCallback, this, _1));

  // trying to fix error
  tf_broadcaster_ = std::make_unique<tf2_ros::TransformBroadcaster>(rclcpp::Node::shared_from_this());

  // Create subscriber to receive the robot_2w odometry. This state is published by gazebo.
  sub_odometry_ = create_subscription<nav_msgs::msg::Odometry>(odom_topic_name_, 10,
                                                               std::bind(&Robot2WCtrl::odom_topic_callback, this, _1));

  // Create subscriber to receive the target position generated by the trajectory generator.
  sub_trajectory_ = create_subscription<geometry_msgs::msg::Point>(
      trajectory_topic_name_, 10, std::bind(&Robot2WCtrl::trajectory_topic_callback, this, _1));

  // Create a publisher to send the commanded robot velocity to the differential drive
  robot_twist_pub_ = create_publisher<geometry_msgs::msg::Twist>(commanded_twist_topic_name_, 10);

  // Create a publisher to plot the pose errors wrt robot frame
  pose_error_pub_ = create_publisher<geometry_msgs::msg::Point>(pose_error_topic_name_, 10);


  // Create a publisher to plot the pose errors wrt robot frame
  pose_pub_ = create_publisher<geometry_msgs::msg::Point>(pose_topic_name_, 10);

  // MAIN control thread. Based on the robot's odom position and the target position, this main thread
  // will compute the controller that generates the cmd_vel
  timer_ =
      this->create_wall_timer(std::chrono::milliseconds(ctrl_period_), std::bind(&Robot2WCtrl::timer_callback, this));


}

Robot2WCtrl::~Robot2WCtrl()
{
}

void Robot2WCtrl::init()
{
  // ROS parameters
  // Declare the ros parameters

  declare_parameter("odom_topic_name", "/odom");
  declare_parameter("trajectory_topic_name", "/path_generator/trajectory");
  declare_parameter("commanded_twist_topic_name", "/cmd_vel");
  declare_parameter("ctrl_gains", std::vector<double>{ 1.0, 1.0, 0.1 });
  declare_parameter("ctrl_period", 1);
  declare_parameter("publish_pose_error", true);
  declare_parameter("pose_error_topic_name", "/pose_error");
  declare_parameter("pose_topic_name", "/pose");

  // Get the ros parameters (for example, from a yaml file or via the console )
  load_parameters();

  RCLCPP_INFO_STREAM(get_logger(), "K:  \n" << K_);
}

rcl_interfaces::msg::SetParametersResult
Robot2WCtrl::parametersCallback(const std::vector<rclcpp::Parameter>& parameters)
{

  // Each time we change the parameters using the terminal, e.g. ros2 param set ...
  // this function will be called, and the input argument "parameters" is populated
  // with the modified parameter. Depending on the name of the parameter, we need
  // to update its corresponding member variable

  rcl_interfaces::msg::SetParametersResult result;
  result.successful = true;
  result.reason = "success";

  RCLCPP_WARN_STREAM(get_logger(), "New parameters [" << parameters.size() << "]");

  for (const auto& param : parameters)
  {
    RCLCPP_INFO_STREAM(get_logger(), param.get_name()
                                         << "<" << param.get_type_name() << ">: " << param.value_to_string());

    if ("odom_topic_name" == param.get_name())
    {
      odom_topic_name_ = param.as_string();
      RCLCPP_INFO_STREAM(get_logger(), "odom_topic_name_: " << odom_topic_name_);
    }

    if ("trajectory_topic_name" == param.get_name())
    {
      trajectory_topic_name_ = param.as_string();
      RCLCPP_INFO_STREAM(get_logger(), "trajectory_topic_name_: " << trajectory_topic_name_);
    }

    if ("commanded_twist_topic_name" == param.get_name())
    {
      commanded_twist_topic_name_ = param.as_string();
      RCLCPP_INFO_STREAM(get_logger(), "commanded_twist_topic_name_: " << commanded_twist_topic_name_);
    }

    if ("ctrl_gains" == param.get_name())
    {
      std::vector<double> k = param.as_double_array();
      // Populate the gain Matrix
      for (size_t i = 0; i < 3; i++)
      {
        K_(i, i) = k.at(i);
      }

      RCLCPP_INFO_STREAM(get_logger(), "K_: \n" << K_.matrix());
    }

    if ("ctrl_period" == param.get_name())
    {
      ctrl_period_ = param.as_int();
      RCLCPP_INFO_STREAM(get_logger(), "ctrl_period_: " << ctrl_period_);
    }

    if ("publish_pose_error" == param.get_name())
    {
      publish_pose_error_ = param.as_bool();
      RCLCPP_INFO_STREAM(get_logger(), "publish_pose_error_: " << publish_pose_error_);
    }
  }

  return result;
}

bool Robot2WCtrl::load_parameters()
{
  // Get the ros parameters (for example, from a yaml file or via the console )
  odom_topic_name_ = get_parameter("odom_topic_name").as_string();
  trajectory_topic_name_ = get_parameter("trajectory_topic_name").as_string();
  commanded_twist_topic_name_ = get_parameter("commanded_twist_topic_name").as_string();
  std::vector<double> k = get_parameter("ctrl_gains").as_double_array();
  ctrl_period_ = get_parameter("ctrl_period").as_int();
  publish_pose_error_ = get_parameter("publish_pose_error").as_bool();
  pose_error_topic_name_ = get_parameter("pose_error_topic_name").as_string();
  pose_topic_name_ = get_parameter("pose_topic_name").as_string();

  // Populate the gain Matrix
  for (size_t i = 0; i < 3; i++)
  {
    K_(i, i) = k.at(i);
  }

  // RCLCPP_WARN_STREAM(get_logger(), "K: \n" << K_.matrix());

  return true;
}

void Robot2WCtrl::odom_topic_callback(const Robot2WOdomShPt msg)
{
  // The variable robot_2w_odom_msg_ will be shared between the subscriber thread and the main control thread
  // We need to protect the reading/writing process using mutex


  // TODO_1: Get the message and assign it to the member variable robot_2w_odom_msg_. 
  // This copy process should be protected with the mutex odom_data_mutex_
  odom_data_mutex_.lock();
  robot_2w_odom_msg_ = msg;
  odom_data_mutex_.unlock(); 
 

  // Flag to control when we have received the robot_2w odometry
  // This flag and the trajectory flag will activate the controller
  got_odom_ = true;
}

void Robot2WCtrl::trajectory_topic_callback(const TrajectoryPointShPt msg)
{
  // The variable robot_2w_odom_msg_ will be shared between the subscriber thread and the main control thread
  // We need to protect the reading/writing process using mutex
  
  // TODO_2: copy the msg to the member variable trajectory_point_msg_. This copy process should 
  // be protected with the mutex trajectory_data_mutex_
  trajectory_data_mutex_.lock();
  trajectory_point_msg_ = msg;
  trajectory_data_mutex_.unlock();

  // Flag to control when we have received the robot_2w odometry
  // This flag and the trajectory flag will activate the controller
  got_traj_point_ = true;
}

void Robot2WCtrl::timer_callback()
{

  // If we have the current robot's pose, and we got a new desired position
  // we start the controller. 
  // 1) Get the current robot's pose (odom) and the target position (target point) from the subscribers.
  // 2) Transform the target position to the robot's frame and calculate the position error
  //    in the robot's frame.
  // 3) Compute the linear velocity in the x_robot axis and the angular velocity 
  //    in the z_robot axis (velocities relative to the robot's frame). This can 
  //    be done using a simple P controller, i.e. v_robot=K*e_robot 

  if (got_odom_ and got_traj_point_)
  {

    // TODO_3: copy the target point obtained by the subscriber into the local variable traj. 
    // This copy process should be protected by the mutex trajectory_data_mutex_
    // Replace the line below with the corresponding copy and mutex
    // TrajectoryPointShPt traj = std::make_shared<geometry_msgs::msg::Point>(); // replace std::make_shared<geometry_msgs::msg::Point>()
    
    trajectory_data_mutex_.lock();
    TrajectoryPointShPt traj = trajectory_point_msg_;
    trajectory_data_mutex_.unlock();

    geometry_msgs::msg::Twist cmd_twist;
    Eigen::Vector3d error_robot;
    geometry_msgs::msg::Point pos;
    geometry_msgs::msg::Quaternion odom_q;

    double roll, pitch, yaw=0.0;

    // By design, you should receive the value z=-1000.0 when 
    // the robot has no more points to follow. 
    // We use that z value to stop the robot, i.e. v_robot=0
    if (traj->z == -1000.0)
    {
      // Set all the cmd velocities to 0 to stop the robot
      cmd_twist.linear.x = 0.0;
      cmd_twist.linear.y = 0.0;
      cmd_twist.linear.z = 0.0;

      cmd_twist.angular.x = 0.0;
      cmd_twist.angular.y = 0.0;
      cmd_twist.angular.z = 0.0;

      error_robot << 0.0, 0.0, 0.0;
    }
    else
    {
      // You are receiving a new desired point to move

      // TODO_4: copy the current odom data from the subscriber into the local variable "odom".
      //  This copy should be protected by the mutex  "odom_data_mutex_"
      // Robot2WOdomShPt odom = std::make_shared<nav_msgs::msg::Odometry>(); // replace std::make_shared<nav_msgs::msg::Odometry>()
      odom_data_mutex_.lock();
      Robot2WOdomShPt odom = robot_2w_odom_msg_;
      odom_data_mutex_.unlock();

      // TODO_5: Extract the robot's position and orientation from "odom" into the variables "pos" and "odom_q"
      // pos = geometry_msgs::msg::Point(); // You need to replace "geometry_msgs::msg::Point()" with the correct value.
      // odom_q = geometry_msgs::msg::Quaternion(); //// You need to replace "geometry_msgs::msg::Quaternion()" with the correct value.
      pos = odom->pose.pose.position; 
      odom_q = odom->pose.pose.orientation;
   
      // Get the orientation as a Rotation matrix
      tf2::Quaternion q(odom_q.x, odom_q.y, odom_q.z, odom_q.w);
      tf2::Matrix3x3 R_robot_odom(q);
      
      if (publish_pose_error_)
        R_robot_odom.getRPY(roll, pitch, yaw);

      // TODO_6: Get the position as a 3D vector
      Eigen::Vector3d pos_robot;
      pos_robot << pos.x, pos.y, pos.z; 


      // TODO_7: Define the transform between robot and odom using the previous rotation
      // and translation
      geometry_msgs::msg::TransformStamped transformStamped;
      transformStamped.header.stamp = now();
      transformStamped.header.frame_id = "odom";
      transformStamped.child_frame_id = "base_link";

      transformStamped.transform.translation.x = pos.x; 
      transformStamped.transform.translation.y= pos.y;
      transformStamped.transform.translation.z= pos.z;

      transformStamped.transform.rotation = odom_q;

      tf_broadcaster_->sendTransform(transformStamped); 



      // TODO_8: Convert the 3D robot position and orientation into an homogeneous Matrix        
      // For this you need to convert the transform into Homogeneous Transformation
      //tf2::Quaternion q(odom_q.x, odom_q.y, odom_q.z, odom_q.w);

      // tf2 transform - similar to turtle code
      tf2::Transform tf_robot_odom;
      tf_robot_odom.setOrigin(tf2::Vector3(pos.x, pos.y, pos.z));
      tf_robot_odom.setRotation(q);

      // transformation matrix
      Eigen::Matrix4d H_robot_odom = Eigen::Matrix4d::Identity();

      // rotation
      for (int i = 0; i < 3; ++i)
      {
        for (int j = 0; j < 3; ++j)
        {
          H_robot_odom(i, j) = tf_robot_odom.getBasis()[i][j];
        }
      }
      
      // translation
      H_robot_odom(0, 3) = tf_robot_odom.getOrigin().x();
      H_robot_odom(1, 3) = tf_robot_odom.getOrigin().y();
      H_robot_odom(2, 3) = tf_robot_odom.getOrigin().z();


      // TODO_9: Compute the Homogeneous transformation of odom wrt robot
      // to find odom wrt robot you need to take the inverse of the homogenous matrix 
      Eigen::Matrix4d H_odom_robot = H_robot_odom.inverse();


      // TODO_10: Define the target point wrt odom as a vector
      Eigen::Vector4d p_target_odom;
      // z is 0 for bc target point is 2D and homogenous coordinate w=1
      p_target_odom << traj->x, traj->y, 0.0, 1.0; 
      

      // TODO_11: Compute the target point wrt to robot.
      // We need to use the homogeneous version of the vector p_t_odom, i.e.,
      // p_t_odom_homogeneous=[p_t_odom;1]^T 
      //Eigen::Vector4d p_target_odom;
      p_target_odom << traj->x, traj->y, 0.0, 1.0;
      Eigen::Vector4d p_target_robot = H_odom_robot * p_target_odom;

      

      // TODO_12: Get the angle in z_robot between the robot and the target point
      double x_r = p_target_robot(0);
      double y_r = p_target_robot(1);
      double angle_robot_target = std::atan2(y_r, x_r);



        
      // TODO_13: Since the target point is represented with respect to the robot frame
      // The position of the target and the angle are the position and
      // orientation errors in the robot frame
     //error_robot << 0.0, 0.0, 0.0; //you need to replace 0.0, 0.0, 0.0 with the correct values
     error_robot << p_target_robot(0), p_target_robot(1), angle_robot_target;


      

      if (publish_pose_error_)
        RCLCPP_INFO_STREAM(get_logger(), "error_robot= " << error_robot.transpose());

      // TODO_14: Compute the cmd velocity using a P-control (Kinematic)
      //Eigen::Vector3d vel = error_robot ; //you need to replace "error_robot" with the correct value
      Eigen::Vector3d vel = K_ * error_robot;

      cmd_twist.linear.x = vel[0];
      //cmd_twist.linear.y = vel[1];  // This can be omitted!
      cmd_twist.linear.y = 0.0;
      cmd_twist.linear.z = 0.0;

      cmd_twist.angular.x = 0.0;
      cmd_twist.angular.y = 0.0;
      cmd_twist.angular.z = vel[2];

    }  // else z not -1000.0

    // We send the calculated velocity wrt the robot's frame as the cmd_vel
    // for the differential drive.
    robot_twist_pub_->publish(cmd_twist);

    if (publish_pose_error_)
    {
      // Publish the pose error wrt robot frame to visualize it in a rqt_plot
      geometry_msgs::msg::Point point_msg;
      point_msg.x = error_robot[0];
      point_msg.y = error_robot[1];
      // Publish the errors in z orientation as DEG
      point_msg.z = RAD2DEG(error_robot[2]);
      pose_error_pub_->publish(point_msg);

      point_msg.x = pos.x;
      point_msg.y = pos.y;
      point_msg.z = RAD2DEG(yaw);

      pose_pub_->publish(point_msg);


    }

  }  // if got_odom and got_traj_point
}

}  // namespace robot_2w_examples
