# Robot2W Controller
robot_2w_control:
  ros__parameters:
    # Odom topic name advertised by Gazebo
    odom_topic_name: "/odom"
    # Topic name to get the target position
    trajectory_topic_name: "/path_generator/trajectory"
    # Topic name to publish the commanded velocity for the differential drive
    commanded_twist_topic_name: "/cmd_vel"
    # control gains
    # TODO_15: Tune the control gains, you need to replace the values inside crtl_gains
    # change these later (controls foward speed, lateral movement, rotation)
    ctrl_gains: [1.0, 0.5, 0.2]
    # control period in ms
    ctrl_period: 1
    # Controls if the pose errors will be published. Useful for debugging the 
    # the controller and its gains. Change this variable to True to publish the tracking errors
    publish_pose_error: True # for debugging
    # Pose error topic name
    pose_error_topic_name: "~/pose_error"
    # Robot's pose topic name
    pose_topic_name: "~/pose"